# Generated by Django 4.1.4 on 2023-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospitalV', '0002_especialidades_imagenes_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='adulto',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='pediatrico',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='estudio',
            field=models.CharField(max_length=50),
        ),
    ]
